ARG TAG=latest

FROM registry.workstation.co.uk/webimpetus:$TAG

RUN apt update && apt upgrade -y && apt install -y \
    curl \
    # git \
    jq \
    vim \
    wget

COPY ci4 /src
COPY config/php/php.ini /usr/local/etc/php
