# This Dockerfile uses the latest version of the Bitnami PHP-FPM Docker image
FROM bitnami/php-fpm:latest

# The application's directory will be the working directory
WORKDIR /app

# Copy app's source code to the /app directory
COPY app-code /app

